networks:
  my_network:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.1.0/24
services:
  node0:
    build: .
    environment:
      NEIGHBORS: 192.168.1.3:500503,192.168.1.6:500506
      NODE_ID: '0'
      NODE_PORT: '500502'
    networks:
      my_network:
        ipv4_address: 192.168.1.2
  node1:
    build: .
    environment:
      NEIGHBORS: 192.168.1.2:500502,192.168.1.4:500504
      NODE_ID: '1'
      NODE_PORT: '500503'
    networks:
      my_network:
        ipv4_address: 192.168.1.3
  node2:
    build: .
    environment:
      NEIGHBORS: 192.168.1.3:500503,192.168.1.5:500505
      NODE_ID: '2'
      NODE_PORT: '500504'
    networks:
      my_network:
        ipv4_address: 192.168.1.4
  node3:
    build: .
    environment:
      NEIGHBORS: 192.168.1.4:500504,192.168.1.6:500506
      NODE_ID: '3'
      NODE_PORT: '500505'
    networks:
      my_network:
        ipv4_address: 192.168.1.5
  node4:
    build: .
    environment:
      NEIGHBORS: 192.168.1.5:500505,192.168.1.2:500502
      NODE_ID: '4'
      NODE_PORT: '500506'
    networks:
      my_network:
        ipv4_address: 192.168.1.6
version: '3.8'
