networks:
  my_network:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.1.0/24
services:
  node0:
    build: .
    environment:
      NEIGHBORS: 192.168.1.3:50053,192.168.1.4:50054,192.168.1.5:50055,192.168.1.6:50056,192.168.1.7:50057,192.168.1.8:50058
      NODE_ID: '0'
      NODE_PORT: 50052
    networks:
      my_network:
        ipv4_address: 192.168.1.2
  node1:
    build: .
    environment:
      NEIGHBORS: 192.168.1.2:50052
      NODE_ID: '1'
      NODE_PORT: 50053
    networks:
      my_network:
        ipv4_address: 192.168.1.3
  node2:
    build: .
    environment:
      NEIGHBORS: 192.168.1.2:50052
      NODE_ID: '2'
      NODE_PORT: 50054
    networks:
      my_network:
        ipv4_address: 192.168.1.4
  node3:
    build: .
    environment:
      NEIGHBORS: 192.168.1.2:50052
      NODE_ID: '3'
      NODE_PORT: 50055
    networks:
      my_network:
        ipv4_address: 192.168.1.5
  node4:
    build: .
    environment:
      NEIGHBORS: 192.168.1.2:50052
      NODE_ID: '4'
      NODE_PORT: 50056
    networks:
      my_network:
        ipv4_address: 192.168.1.6
  node5:
    build: .
    environment:
      NEIGHBORS: 192.168.1.2:50052
      NODE_ID: '5'
      NODE_PORT: 50057
    networks:
      my_network:
        ipv4_address: 192.168.1.7
  node6:
    build: .
    environment:
      NEIGHBORS: 192.168.1.2:50052
      NODE_ID: '6'
      NODE_PORT: 50058
    networks:
      my_network:
        ipv4_address: 192.168.1.8
version: '3.8'
