# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: network_manager.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'network_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15network_manager.proto\x12\x07network\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x1d\n\x0cMessageCount\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32\x87\x01\n\x0bNodeService\x12\x38\n\rGossipMessage\x12\x17.network.MessageRequest\x1a\x0e.network.Empty\x12>\n\x15GetUniqueMessageCount\x12\x0e.network.Empty\x1a\x15.network.MessageCountb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=34
  _globals['_MESSAGEREQUEST']._serialized_end=67
  _globals['_EMPTY']._serialized_start=69
  _globals['_EMPTY']._serialized_end=76
  _globals['_MESSAGECOUNT']._serialized_start=78
  _globals['_MESSAGECOUNT']._serialized_end=107
  _globals['_NODESERVICE']._serialized_start=110
  _globals['_NODESERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
